spring.application.name=expense-tracker

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update

spring.ai.ollama.base-url=http://localhost:11434

jwt.secret-key=${SECRET_KEY}
jwt.expiration-time-access-time=600
jwt.expiration-time-refresh-time=3600

redis.host=localhost
redis.port=6379