spring.application.name=expense-tracker
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}

app.data-initializer.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=${GEMINI_MODEL:gemini-2.5-flash}
spring.ai.google.genai.chat.temperature=0.2

jwt.secret-key=${SECRET_KEY}
jwt.expiration-time-access-time=${JWT_ACCESS_EXPIRATION_SECONDS:600}
jwt.expiration-time-refresh-time=${JWT_REFRESH_EXPIRATION_SECONDS:3600}

redis.host=${REDISHOST}
redis.port=${REDISPORT}
redis.username=${REDISUSER}
redis.password=${REDISPASSWORD}

server.port=${PORT:8080}

logging.level.root=INFO
logging.level.com.project.expensetracker=INFO
