spring.application.name=expense-tracker
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://ollama:11434}

jwt.secret-key=${SECRET_KEY}
jwt.expiration-time-access-time=${JWT_ACCESS_EXPIRATION_SECONDS:600}
jwt.expiration-time-refresh-time=${JWT_REFRESH_EXPIRATION_SECONDS:3600}

redis.host=${REDIS_HOST:redis}
redis.port=${REDIS_PORT:6379}

server.port=${PORT:8080}

logging.level.root=INFO
logging.level.com.project.expensetracker=INFO
