spring.application.name=expense-tracker

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:3000}

app.data-initializer.enabled=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=${GEMINI_MODEL:gemini-2.5-flash}
spring.ai.google.genai.chat.temperature=0.2

jwt.secret-key=${SECRET_KEY}
jwt.expiration-time-access-time=600
jwt.expiration-time-refresh-time=3600

redis.host=localhost
redis.port=6379
redis.username=
redis.password=
